# https://github.com/DavidAnson/markdownlint
# https://github.com/DavidAnson/markdownlint-cli2

globs:
  - "**/*.md"

ignores:
  - ".git/**"
  - ".github/**"

config:
  # MD013/line-length
  MD013: false
  # h1
  MD025: false
  # inline HTML
  MD033: false
