name: Lint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # https://github.com/marketplace/actions/markdownlint-cli2-action
      # https://github.com/DavidAnson/markdownlint-cli2-action
      - uses: DavidAnson/markdownlint-cli2-action@v13
