name: Lint

on:
  push:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache:  'npm'

      - run: npm install --global markdownlint-cli2

      - run: markdownlint-cli2
